In [1]:
import pandas as pd
import numpy as np
import ast
import json
from sqlalchemy import create_engine
from sentence_transformers import SentenceTransformer

from mappings import *

C:\Users\ADMIN\Desktop\Dev\Python\LLM_recipe_recommender\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
path = r"..\data\raw_recipes_dataset.csv"
#path = r"C:\Users\ADMIN\Desktop\Pliki\Datasets\recipes_dataset.csv"

engine = create_engine('mysql+pymysql://dev:dev@localhost:3306/recipe_app')

### 1. Reading in the raw file, cleaning the data and saving as a staging table

In [3]:
df_main = pd.read_csv(
    path, 
    encoding='ISO-8859-1', 
    sep=';', 
    quotechar='"', 
    on_bad_lines='skip' # Skips the lines that are truly broken
)

In [4]:
df = df_main.copy()
df.head(3)

,Name,Author,Date,Rating Value,Rating Count,Preparation Time,Cooking Time,Category,Cuisine,Ingredients,Ingredients_Raw,Instructions,Cooking Methods,Implements,Number of steps,Servings,Nutrition,URL
0,Pineapple Glaze for Ham,Jackie,01/04/2025,4.5,104.0,10.0,5.0,['Dinner'],['American'],"[{'ingredient': 'pineapple', 'quantity': '1', ...","['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],4.0,"['14', '3 cups']","{'Calories': '93 kcal', 'Carbohydrates': '24 g...",https://www.allrecipes.com/recipe/17116/pineap...
1,Awesome Egg Rolls,ROUVER,01/04/2025,4.5,299.0,35.0,15.0,"['Dinner', 'Appetizer']","['World', 'Asian']","[{'ingredient': 'vegetable oil', 'quantity': '...","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']",11.0,"['10', '20 egg rolls']","{'Calories': '1268 kcal', 'Carbohydrates': '57...",https://www.allrecipes.com/recipe/84099/awesom...
2,Spanish Tortilla,Leslie Rosas,01/04/2025,4.3,15.0,10.0,10.0,['Breakfast'],['Spanish'],"[{'ingredient': 'olive oil', 'quantity': '0.25...","['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],3.0,4,"{'Calories': '447 kcal', 'Carbohydrates': '22 ...",https://www.allrecipes.com/recipe/24342/spanis...

### getting rid of nulls and reformatting list and dict columns

In [5]:
def safe_literal_eval(x):
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return None

df['Ingredients'] = df['Ingredients'].apply(safe_literal_eval)
df['Cuisine'] = df['Cuisine'].apply(safe_literal_eval)
df['Category'] = df['Category'].apply(safe_literal_eval)
df['Cooking Methods'] = df['Cooking Methods'].apply(safe_literal_eval)
df['Implements'] = df['Implements'].apply(safe_literal_eval)

# Dropping columns
df = df[df['Ingredients'].notna()]
df = df.drop(["Author", "Servings"], axis=1)

# Cleaning Instructions text
df['Instructions'] = df['Instructions'].str.replace(r"[\[\]']", "", regex=True)

# Adding ID
df.insert(0, 'ID', range(1, len(df) + 1))

# Changing Data column to proper datatype
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")

# Generalising dish categories
df['Category'] = df['Category'].apply(
    lambda x: list(dict.fromkeys([category_mapping.get(item, item) for item in x])))

# Generalising cuisines
def categorize_cuisines(x):
    if not x or len(x) == 0:
        return "World / Fusion"
    
    c_list = []
    for c in x:
        mapped_val = cuisine_mapping.get(c, "World / Fusion")
        if len(x) > 1 and mapped_val == "World / Fusion":
            continue
        else:
            c_list.append(mapped_val)
            
    return c_list[0]

df["Cuisine"] = df["Cuisine"].apply(categorize_cuisines)

In [6]:
# Simplify Ingredients column:
def extract_ingredients(x):
    ingredients = []
    for ingredient_dict in x:
        ingredients.append(ingredient_dict["ingredient"])
    return ingredients

df["Ingredients"] = df['Ingredients'].apply(extract_ingredients)

In [7]:
df["Rating Count"] = df["Rating Count"].astype("Int64")
df["Number of steps"] = df["Number of steps"].astype("Int64")

df.columns = (
    df.columns
      .str.strip()
      .str.replace(r"\s+", "_", regex=True)
)
df = df.rename(columns={'Date': 'created_at'})

In [8]:
# Lowercase all the columns and filter out recipies without ratings
df.columns = df.columns.str.lower()
df = df[
    df["name"].notna()
    & df["ingredients"].notna()
    & df["instructions"].notna()
    & (df["rating_count"] >= 5)
]

#### Ingesting staging table to the database

In [10]:
json_cols = [
    "category",
    "ingredients",
    "ingredients_raw",
    "cooking_methods",
    "implements",
    "nutrition"
]

def to_json_safe(x):
    if x is None:
        return None
    if isinstance(x, float) and np.isnan(x):
        return None
    return json.dumps(x)

for c in json_cols:
    df[c] = df[c].apply(to_json_safe)

In [11]:
df.head(3)

,id,name,created_at,rating_value,rating_count,preparation_time,cooking_time,category,cuisine,ingredients,ingredients_raw,instructions,cooking_methods,implements,number_of_steps,nutrition,url
0,1,Pineapple Glaze for Ham,2025-04-01,4.5,104,10.0,5.0,"[""Main Course""]",North American,"[""pineapple"", ""maraschino cherries"", ""brown su...","""['1 (15.25 ounce) can sliced pineapple, drain...","Gather the ingredients., Before baking ham, pl...","[""microwave""]","[""microwave""]",4,"""{'Calories': '93 kcal', 'Carbohydrates': '24 ...",https://www.allrecipes.com/recipe/17116/pineap...
1,2,Awesome Egg Rolls,2025-04-01,4.5,299,35.0,15.0,"[""Main Course"", ""Starters & Snacks""]",Asian,"[""vegetable oil"", ""egg"", ""cabbage"", ""bean spro...","""['1 tsp vegetable oil', '1 egg, beaten', '6 c...","Gather all ingredients., Mix cabbage, bean spr...","[""fry""]","[""skillet"", ""cutting board""]",11,"""{'Calories': '1268 kcal', 'Carbohydrates': '5...",https://www.allrecipes.com/recipe/84099/awesom...
2,3,Spanish Tortilla,2025-04-01,4.3,15,10.0,10.0,"[""Breakfast & Brunch""]",Mediterranean,"[""olive oil"", ""potatoes"", ""bacon"", ""ham"", ""oni...","""['0.25 cup olive oil', '2 potatoes, peeled', ...",Slice edges off of potatoes so that potatoes a...,"[""fry""]","[""skillet""]",3,"""{'Calories': '447 kcal', 'Carbohydrates': '22...",https://www.allrecipes.com/recipe/24342/spanis...

In [12]:
not_loaded_data = []
for start in range(0, len(df), 10_000):
    cur_df = df.iloc[start:start+10_000]
    try:
        cur_df.to_sql(
            name="recipes_staging",
            con=engine,
            if_exists="append",
            index=False,
            method="multi"
        )
        print("part_uploaded")
    except Exception as e: # 'Exception' is the base class, 'e' is the instance
        print(f"Failed to upload batch starting at {start}")
        print(f"Error type: {type(e).__name__}") # Tells you if it's a ConnectionError, OperationalError, etc.
        print(f"Error message: {e}")             # The actual error text
        not_loaded_data.append(cur_df)

part_uploaded
part_uploaded
part_uploaded
part_uploaded

### 2. Running the notebook `ingredients_classifier.ipynb`

- It extracts unique ingredients and simplifies them (low-sodium soy sauce -> soy sauce)
- It classifies them for dietary requirements (vegan, gluten_free, halal etc.)
- It creates a table `ingredients_main` with mapping (original ingredient -> simplified ingredient -> dietary classification

### 3. Enrich the staging data with ingredient specific information and saving final table `ingredients_main`

In [76]:
QUERY_INGREDIENTS = """
    SELECT distinct * FROM ingredients_main
"""
QUERY_SOURCE = """
    SELECT * FROM recipes_staging
"""

df = pd.read_sql_query(QUERY_SOURCE, con=engine)
df_ingredients = pd.read_sql_query(QUERY_INGREDIENTS, con=engine)
map = df_ingredients.set_index('original')['ingredient'].to_dict()
df_ingredients.head(2)

,original,ingredient,vegan,vegetarian,gluten_free,halal,kosher,keto_friendly
0,bbq rub,bbq rub,1.0,1.0,0.0,1.0,1.0,1.0
1,toasted almonds,almonds,1.0,1.0,1.0,1.0,1.0,1.0

#### Add `ingredients_normalized` column based on mapping from ingredients

In [77]:
def normalize_ingredients(input_str, ingredients_mapping):
    output_list = []
    list = ast.literal_eval(input_str)
    for i in list:
        if i in ingredients_mapping:
            output_list.append(ingredients_mapping[i])
        elif i in ingredients_mapping.values():
            output_list.append(i)
    return output_list

In [78]:
df["ingredients_normalized"] = df["ingredients"].apply(normalize_ingredients, ingredients_mapping=map)

In [79]:
diet_cols = [
    "vegan",
    "vegetarian",
    "gluten_free",
    "keto_friendly",
    "halal",
    "kosher"
]

ingredient_lookup = (
    df_ingredients.drop(columns="original").drop_duplicates()
    .set_index("ingredient")[diet_cols]
    .to_dict(orient="index")
)

In [82]:
def is_vegan(ingredient_list):
    #ingredient_list = ast.literal_eval(ingredient_list)
    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            return False
        elif ingredient_lookup.get(i, 0).get("vegan", 0) == 0:
            return False
    return True
def is_vegetarian(ingredient_list):
    #ingredient_list = ast.literal_eval(ingredient_list)
    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            return False
        elif ingredient_lookup.get(i, 0).get("vegetarian", 0) == 0:
            return False
    return True
def is_gluten_free(ingredient_list):
    #ingredient_list = ast.literal_eval(ingredient_list)
    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            return False
        elif ingredient_lookup.get(i, 0).get("gluten_free", 0) == 0:
            return False
    return True
def is_halal(ingredient_list):
    #ingredient_list = ast.literal_eval(ingredient_list)
    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            return False
        elif ingredient_lookup.get(i, 0).get("halal", 0) == 0:
            return False
    return True
def is_kosher(ingredient_list):
    #ingredient_list = ast.literal_eval(ingredient_list)
    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            return False
        elif ingredient_lookup.get(i, 0).get("kosher", 0) == 0:
            return False
    return True
def is_keto_friendly(ingredient_list):
    l = len(ingredient_list)

    if l == 0:
        return False

    keto_score = 0

    for i in ingredient_list:
        if ingredient_lookup.get(i, 0) == 0:
            pass
        elif ingredient_lookup.get(i, 0).get("keto_friendly", 0) == 1:
            keto_score += 1

    score = keto_score / l

    return score > 0.85

In [83]:
df["is_vegan"] = df["ingredients_normalized"].apply(is_vegan)
df["is_vegetarian"] = df["ingredients_normalized"].apply(is_vegetarian)
df["is_gluten_free"] = df["ingredients_normalized"].apply(is_gluten_free)
df["is_halal"] = df["ingredients_normalized"].apply(is_halal)
df["is_kosher"] = df["ingredients_normalized"].apply(is_kosher)
df["keto_friendliness"] = df["ingredients_normalized"].apply(is_keto_friendly)

In [84]:
df_backup = df

### Adding the table to database

In [85]:
json_cols = [
    "category",
    "ingredients",
    "ingredients_normalized",
    "ingredients_raw",
    "cooking_methods",
    "implements",
    "nutrition"
]

def to_json_safe(x):
    # 1. Handle nulls
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None

    # 2. If it's already a string, parse it to a Python object first
    if isinstance(x, str):
        try:
            x = json.loads(x)
        except json.JSONDecodeError:
            # Fallback if it's a plain string and not a JSON string
            pass

    # 3. Serialize it cleanly once
    return json.dumps(x)

for c in json_cols:
    df[c] = df[c].apply(to_json_safe)

In [86]:
df["ingredients"][0]

'["pineapple", "maraschino cherries", "brown sugar"]'

In [87]:
not_loaded_data = []
for start in range(0, len(df), 10_000):
    cur_df = df.iloc[start:start+10_000]
    try:
        cur_df.to_sql(
            name="recipes_main",
            con=engine,
            if_exists="append",
            index=False,
            method="multi"
        )
        print("part_uploaded")
    except Exception as e: # 'Exception' is the base class, 'e' is the instance
        print(f"Error type: {type(e).__name__}") # Tells you if it's a ConnectionError, OperationalError, etc.
        print(f"Error message: {e}")             # The actual error text
        not_loaded_data.append(cur_df)

part_uploaded
part_uploaded
part_uploaded
part_uploaded

In [24]:
# Filtering rows where 'Fusion' is present in the list
df['Cuisine'] = df['Cuisine'].apply(safe_literal_eval)
filtered_df = df[df['Cuisine'].apply(lambda x: 'Fusion' in x if isinstance(x, list) else False)]
filtered_df

,Name,Author,Date,Rating Value,Rating Count,Preparation Time,Cooking Time,Category,Cuisine,Ingredients,Ingredients_Raw,Instructions,Cooking Methods,Implements,Number of steps,Servings,Nutrition,URL
28,Steak and Mushroom Tortellini Alfredo,thedailygourmet,31/03/2025,4.8,4.0,20.0,20.0,['Dinner'],"[American, Fusion, Italian]","[{'ingredient': 'olive oil', 'quantity': '2', ...","['2 tablespoons olive oil', '1 tablespoon soy ...","['Whisk olive oil, soy sauce, and steak season...",['boil'],"['whisk', 'skillet', 'saucepan', 'pot']",5.0,10,"{'Calories': '431 kcal', 'Carbohydrates': '28 ...",https://www.allrecipes.com/recipe/277460/steak...
119,Teriyaki and Pineapple Chicken,HEZZZ1223,31/03/2025,4.4,325.0,15.0,25.0,['Dinner'],"[Fusion, Hawaiian, Japanese]","[{'ingredient': 'vegetable oil', 'quantity': '...","['2 tablespoons vegetable oil', '1 pound skinl...",['Heat oil in a wok or large skillet over medi...,"['simmer', 'reduce']","['skillet', 'wok']",2.0,8,"{'Calories': '187 kcal', 'Carbohydrates': '18 ...",https://www.allrecipes.com/recipe/62124/teriya...
256,What the ELLE...Baked Egg Rolls,HoneyBooBoo,27/03/2025,4.3,27.0,15.0,20.0,"['Appetizer', 'Snack']","[Asian Inspired, Fusion]","[{'ingredient': 'carrots', 'quantity': '2', 'u...","['2 cups grated carrots', '1 (14.5 ounce) can ...",['Preheat oven to 425 degrees F (220 degrees C...,"['bake', 'boil']","['skillet', 'oven', 'baking sheet']",5.0,"['8', '8 servings']","{'Calories': '150 kcal', 'Carbohydrates': '17 ...",https://www.allrecipes.com/recipe/222602/what-...
262,Creamy Bang Bang Shrimp Pasta,Bibi,27/03/2025,4.6,5.0,10.0,15.0,['Dinner'],"[American, Fusion]","[{'ingredient': 'fettuccine pasta', 'quantity'...",['0.5 (16 ounce) package dry fettuccine pasta'...,['Fill a large pot with lightly salted water a...,['boil'],"['whisk', 'skillet', 'pot']",4.0,"['2', '2 servings']","{'Calories': '891 kcal', 'Carbohydrates': '103...",https://www.allrecipes.com/recipe/278278/cream...
383,Kamikaze Burgers,Jethro Beltran,26/03/2025,4.2,26.0,20.0,30.0,['Dinner'],[Fusion],"[{'ingredient': 'lean beef', 'quantity': '1', ...","['1 pound lean ground beef', '0.25 cup minced ...","['In a large bowl, mix ground beef, onion and ...",['grill'],['grill'],4.0,"['4', '4 burgers']","{'Calories': '604 kcal', 'Carbohydrates': '33 ...",https://www.allrecipes.com/recipe/19925/kamika...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18061,Puffed Wheat Squares,The Schmidts,17/07/2024,5.0,13.0,10.0,5.0,"['Snack', 'Dessert']","[Canadian, Fusion]","[{'ingredient': 'puffed wheat cereal', 'quanti...","['10 cups puffed wheat cereal', '1 cup corn sy...",['Grease a 9x13-inch pan. Place cereal in a la...,['boil'],"['saucepan', 'pan']",3.0,"['24', '24 squares']","{'Calories': '135 kcal', 'Carbohydrates': '26 ...",https://www.allrecipes.com/recipe/234014/puffe...
18139,Buffalo Chicken Totchos,Soup Loving Nicole,13/07/2024,5.0,3.0,15.0,30.0,"['Dinner', 'Appetizer']","[American, Mexican, Fusion]",[{'ingredient': 'frozen bite-size potato nugge...,['1 (32 ounce) package frozen bite-size potato...,['Preheat the oven to 450 degrees F (230 degre...,"['bake', 'broil']","['baking sheet', 'oven', 'skillet']",8.0,8,"{'Calories': '481 kcal', 'Carbohydrates': '32 ...",https://www.allrecipes.com/recipe/274602/buffa...
18254,Easy Chile Relleno Egg Rolls,MizzWycked,07/07/2024,4.7,6.0,30.0,10.0,"['Appetizer', 'Snack']","[Mexican Inspired, Fusion, Mexican, Asian]","[{'ingredient': 'egg roll wrappers', 'quantity...","['2 (12 ounce) packages egg roll wrappers', '1...","['Lay a wrapper on a work surface diagonally, ...",['fry'],"['frying pan', 'pan']",4.0,"['24', '24 egg rolls']","{'Calories': '175 kcal', 'Carbohydrates': '18 ...",https://www.allrecipes.com/recipe/270418/easy-...
19045,Air Fryer Pasta Chips,Soup Loving Nicole,13/05/2024,4.5,17.0,5.0,40.0,"['Appetizer', 'Snack']","[American, Italian, Fusion]","[{'ingredient': 'farfalle pasta', 'quantity': ...","['2 cups farfalle pasta', '1 tablespoon olive ...","['Gather all ingredients.', 'Bring a large pot...",['boil'],['pot'],7.0,8,"{'Calories': '72 kcal', 'Carbohydrates': '7 g'...",https://www.allrecipes.com/recipe/279396/air-f...
22559,Air Fryer Prosciutto and Mozzarella Grilled Ch...,France C,21/08/2023,5.0,3.0,5.0,10.0,['Lunch'],"[American, Italian, Fusion]","[{'ingredient': 'unsalted butter', 'quantity':...","['2 tablespoons unsalted butter, softened', '2...",['Preheat the oven to 360 degrees F (180 degre...,[],['oven'],3.0,"['1', '1 sandwich']","{'Calories': '774 kcal', 'Carbohydrates': '31 ...",https://www.allrecipes.com/recipe/279394/air-f...

In [13]:
### GOT TO BE DONE BEFORE GENERALIZING CUISINES
# all_cusines = {item 
#                    for ingredient_list in df['Cuisine'] 
#                    for item in ingredient_list}
# len(all_cusines)
# all_cusines

In [75]:
all_categories = {item 
                   for ingredient_list in df['Category'] 
                   for item in ingredient_list}
len(all_categories)

13

In [76]:
all_categories

{'Bread',
 'Breakfast & Brunch',
 'Drinks',
 'Main Course',
 'Pantry & Ingredients',
 'Salad',
 'Sandwich',
 'Sauce',
 'Side Dish',
 'Soup',
 'Spice Mix',
 'Starters & Snacks',
 'Sweets & Desserts'}

In [10]:
all_cooking_methods = {item 
                   for ingredient_list in df['Cooking Methods'] 
                   for item in ingredient_list}
len(all_cooking_methods)

22

In [11]:
all_implementations = {item 
                   for ingredient_list in df['Implements'] 
                   for item in ingredient_list}
len(all_implementations)

47

In [18]:
# df["Ingredients_Raw"][0]
df["Instructions"][0]

"['Gather the ingredients.', 'Before baking ham, place pineapple slices on ham with toothpicks and place cherries in center of pineapple.', 'Combine brown sugar and reserved pineapple juice in a medium microwave-safe bowl. Mix and microwave for about 5 minutes, until mixture is thick.', 'Pour some of this glaze over the ham about every 15 minutes in the last hour of baking, until all is used.']"

In [23]:
df["Servings"]

0                     ['14', '3 cups']
1               ['10', '20 egg rolls']
2                                    4
3                                    6
4        ['16', '2 (8x4-inch) loaves']
                     ...
50508           ['6', '6 large rolls']
50509        ['4', '4 salmon fillets']
50510            ['8', '1 9-inch pie']
50511              ['4', '4 servings']
50512            ['10', '10 servings']
Name: Servings, Length: 50511, dtype: object

In [10]:
df2

,ID,Ingredients,Category,Cuisine,Cooking Methods
0,1,"[, jar, cup]",[Dinner],North American,[microwave]
1,2,"[tsp, , cups, cup, , celery, tablespoons, , ta...","[Dinner, Appetizer]",East Asian,[fry]
2,3,"[cup, , slices, slices, , red, , teaspoon]",[Breakfast],Mediterranean,[fry]
3,4,"[bunch, cup, cup, tablespoons, garlic, tablesp...",[Dinner],North American,[grill]
4,5,"[cooking, cups, teaspoon, teaspoon, cup, cups,...",[Brunch],North American,[bake]
...,...,...,...,...,...
50508,50507,"[cup, tablespoon, , cup, cup, cups, cup, teasp...",[Breakfast],North American,[bake]
50509,50508,"[skin-on, fluid, tablespoon, clove, teaspoon, ...",[Dinner],World / Generic,[grill]
50510,50509,"[, fluid, tub, prepared, tablespoon]",[Dessert],World / Generic,[]
50511,50510,"[, cup, cup, pounds, , cup, teaspoon, , , cup,...",[Dinner],Fusion & Inspired,"[simmer, boil]"
50512,50511,"[pounds, cup, large, teaspoons, teaspoon, tabl...","[Dinner, Side Dish]",World / Generic,"[bake, simmer, boil, reduce]"

### getting distinct values for ingredients and units

### Cleaning unique ingredients set
Needs to be run after extract ingredients function

In [42]:
unique_items = set(
    item
    for sublist in df["Ingredients"]
    for item in sublist
)
len(unique_items)

17037

In [43]:
# Cleaning by patterns
phrases = ["cover", "skinned", "peeled", "ounce", "frozen", "cooked", "cup", "bone", "gram", "halved", "plus", "pound", "thick"]

digits = {item for item in unique_items if any(char.isdigit() for char in item)}
long_items = {item for item in unique_items if len(item) > 16}
short_items = {item for item in unique_items if len(item) <= 2}
or_items = {item for item in unique_items if "or " in item or " or" in item}
and_items = {item for item in unique_items if "and " in item or " and" in item}
of_items = {item for item in unique_items if "of " in item or " of" in item}
phrases_items = {item for item in unique_items if any(phrase in item for phrase in phrases)}

# Remove them from the set
unique_items -= digits | long_items | short_items | or_items | and_items | of_items | phrases_items

In [44]:
len(unique_items)

5641

In [125]:
test_items = {item for item in unique_items if "thick" in item}
test_items

In [117]:
df_ingredients = pd.DataFrame({
    'ingredients': list(unique_items),
    'vegan': '',
    'vegetarian': '',
    'gluten_free': '',
    'keto_friendly': '',
    'halal': '',
    'kosher': '',
})
df_ingredients.head()

        ingredients vegan vegetarian gluten_free keto_friendly halal kosher
0        palm sugar
1  agar-agar powder
2         jackfruit
3       smoked tofu
4         hemp milk

In [118]:
path = r"C:\Users\ADMIN\Desktop\Pliki\Datasets\empty_ingredients.csv"
df_ingredients.to_csv(path, index=False)

In [131]:
path = r"C:\Users\ADMIN\Desktop\Pliki\Datasets\ingredients_classified.csv"

df_classified = pd.read_csv(path)
df_classified = df_classified.drop_duplicates(subset=["ingredients"], keep="first")
df_classified = df_classified.rename(columns={'ingredients': 'ingredient'})
df_classified.head()

,ingredient,vegan,vegetarian,gluten_free,keto_friendly,halal,kosher
0,palm sugar,1,1,1,0,1,1
1,agar-agar powder,1,1,1,1,1,1
2,jackfruit,1,1,1,1,1,1
3,smoked tofu,1,1,1,1,1,1
4,hemp milk,0,1,1,1,1,1

In [ ]:
"cover", "skinned", "peeled", "ounce"

In [82]:
unique_items

{'frozen bell pepper',
 'hamburger patties',
 'smoked tofu',
 'frozen tater tots',
 'flax',
 'caramel chips',
 'tenderloin filets',
 'pop sticks',
 'bean',
 'coconut sap',
 'pork sage sausage',
 'whole wheat flour',
 'red bean curd',
 'japanese milk bread',
 'pumpkin pie filling',
 'angel food cake mix',
 'petite tomatoes',
 'aleppo pepper flakes',
 'focaccia bread',
 'pastrami',
 'leftover turkey meat',
 'parsnips',
 'baby red potatoes',
 'baby eggplants',
 'coarsely venison',
 'chipotle spice rub',
 'white raisins',
 'white baking chips',
 'low-sodium broth',
 'blueberry jelly',
 'slaw',
 'kraft cheddar cheese',
 'yellow lentils',
 'hawaiian marinade',
 'strawberry syrup',
 'spinach fettuccine',
 'canned lima beans',
 'top round roast',
 'vinaigrette',
 'beef sirloin roast',
 'pear',
 'peel in',
 'turkey meat',
 'cut up vegetables',
 'rice wine',
 'coarsely coriander',
 'oxtail soup mix',
 'basil pesto sauce',
 'red quinoa',
 'frozen turnip greens',
 'dark jamaican rum',
 'sweet barbeque sauce',
 'whole grain quinoa',
 'raspberry schnapps',
 'cod',
 'flax seeds',
 'dates',
 'goya recaito',
 'crust pastries',
 'pickled jalapeno',
 'soy milk',
 'chorizo sausage',
 'fruit rolls',
 'pipe rigate pasta',
 'bread flour',
 'pork stock',
 'currant jelly',
 'skyr',
 'zucchini blossoms',
 'oil-packed garlic',
 'multigrain bread',
 'ketchup',
 'pernod',
 'chicken leg meat',
 'peruano beans',
 'pickled beets',
 'containers',
 'shells',
 'pineapple skin',
 'mung bean',
 'sweet wine',
 'bread round',
 'aji nori furikake',
 'salad oil',
 'banana',
 'craisins',
 'coconut water',
 'bulbs',
 'seasoning to taste',
 'blue hubbard squash',
 'coarsely grits',
 'seedless rye bread',
 'red candies',
 'blackberry juice',
 'japanese rice wine',
 'licorice root',
 'ribs leaves',
 'cleaned baby squid',
 'lemon oil',
 'whole anise seeds',
 'breast tenderloins',
 'pork tenderloin',
 'capers brine',
 'mango flavored rum',
 'vegetable juice',
 'lightly cilantro',
 'parmesan cheese rind',
 'wheat pita breads',
 'instant corn masa',
 'slice',
 'square dinner rolls',
 'garam masala',
 'spanish onions',
 'bibb lettuce',
 'goya sauce',
 'drumsticks skin',
 'brown onion',
 'hawaiian sea salt',
 'center pork chops',
 'lobster claw',
 'oxtails',
 'leg confit',
 'milk chocolate',
 'cocoa mix',
 'bologna',
 'goya pineapple',
 'liquid lecithin',
 'whip cream',
 'pickling salt',
 'beef chuck',
 'candied fruit peel',
 'center-cut bacon',
 'thai red rice',
 'beef sirloin tips',
 'orzo',
 'frozen chitterlings',
 'hibiscus petals',
 'lemon grass puree',
 'crescent rolls',
 'angostura bitters',
 'spiral cut ham',
 'sesame chili oil',
 'creamed',
 'cream soda',
 'leftover roast beef',
 'bottled chili sauce',
 'fah chiles',
 'french chestnuts',
 'cilantro sprigs',
 'dill pickle slices',
 'skim milk powder',
 'saffron rice',
 'mints girl scout',
 'gummy bears',
 'orange flavoring',
 'fake bacon bits',
 'watercress - rinsed',
 'zhug sauce',
 'barely boiling water',
 'spicy chili powder',
 'skirt steak',
 'london broil steak',
 'fudge stripe cookies',
 'chunky peanut butter',
 'canned chicken broth',
 'fuyu persimmons',
 'legs skin',
 'black tea',
 'black fondant',
 'pecan liqueur',
 'white gumdrops',
 'fish broth',
 'asian chili paste',
 'canned pineapple',
 'frozen banana slices',
 'young ginger root',
 'lukewarm water',
 'frozen puff pastry',
 'snipped rosemary',
 'chocolate fettuccine',
 'spears to garnish',
 'rutabaga',
 'jars lids',
 'ginger',
 'pickle chips',
 'rosemary leaves',
 'mexican rice mix',
 'broccolini',
 'anise pods',
 'garlic potato flakes',
 'salted cashew halves',
 'charcoal briquettes',
 'vermont maple syrup',
 'parmesan sauce',
 'chinese noodles',
 'corn on the cob',
 'masala curry sauce',
 'top-sirloin steak',
 'asian chile sauce',
 'jumbo prawns',
 'shrimp - shells on',
 'orange roughy',
 'flounder fillets',
 'classic coleslaw mix',
 'fettuccini pasta',
 'whole grain mustard',
 'original pretzel',
 'leaves',
 'green olive',
 'seafood',
 'canned cream corn',
 'mini farfalle pasta',
 'sushi-grade ahi tuna',
 'roast',
 'tumeric',
 'marzipan',
 'chicken broth base',
 'new potatoes',
 'heirloom tomato',
 'egg yolks',
 'soft',
 'thin bacon',
 'slices challah bread',
 'spanish paprika',
 'whole kingfish',
 'fermented bean paste',
 'jalapeno salsa',
 'salami',
 'assorted greens',
 'frozen shrimp tails',
 'barolo red wine',
 'milled flax seed',
 'asian slaw mix',
 'whole cashews',
 'light rye bread',
 'wide vegan noodles',
 'white potato',
 'canned tomato paste',
 'beef top round steak',
 'pastina pasta',
 'goya salsita',
 'sausage link',
 'pork heart',
 'semolina flour',
 'vidalia',
 'paper cups',
 'roast beef gravy',
 'veal scaloppini',
 'champagne vinegar',
 'lager beer',
 'firm pears',
 'sweet gherkin pickle',
 'asian plum wine',
 'black walnuts',
 'almond-coconut milk',
 'mini bell peppers',
 'slice jalapeno slice',
 'beef prime rib roast',
 'taco corn tortillas',
 'black garlic',
 'infant oat cereal',
 'mexican-blend cheese',
 'strawberry liqueur',
 'penne',
 'vermicelli',
 'mostaccioli',
 'lard',
 'crab boil',
 'snow crab clusters',
 'julienned carrot',
 'coarse bulgur',
 'soft bread',
 'flat leaf parsley',
 'canned chili starter',
 'pasilla chiles',
 'raspberry sorbet',
 'chai concentrate',
 'red chile sauce',
 'peanut butter chips',
 'purple onion',
 'fresno pepper',
 'demi-glace',
 'pastry discs',
 'chicken hearts',
 'vanilla powder',
 'frozen pound cake',
 'pork butt roast',
 'flaked tuna',
 'yellowtail flounder',
 'yellow shoepeg corn',
 'flaked almonds',
 'slice watermelon',
 'beef short ribs',
 'butter spread',
 'stout beer',
 'seedless raisins',
 'baking spray',
 'umeboshi',
 'pear halves in juice',
 'rice sides" - beef',
 'maple roll sausage',
 'sweet chilli sauce',
 'french onion soup',
 'bonnet chiles',
 'duck breast halves',
 'vanilla vodka',
 'sprouts',
 'shoulder steaks',
 'puff pastry shells',
 'non-iodized salt',
 'tortilla strips',
 'candy bars',
 'cherry wood chips',
 'grass-fed gelatin',
 'canned tomatoes',
 'boar\x19s curry chicken',
 'frozen crowder peas',
 'lite soy sauce',
 'thin breadsticks',
 'oysters in shells',
 'sea saltkosher salt',
 'sherry wine vinegar',
 'yellow squash',
 'ready pasta rotini',
 'chayote squash',
 'grape flavored mix',
 'wild turkey breast',
 'angel hair pasta',
 'powdered sugar',
 'berbere seasoning',
 'firmly brown sugar',
 'pomegranate molasses',
 'tempura shrimp',
 'black sesame seeds',
 'orange-flower water',
 'bread',
 'king crab legs',
 'mild',
 'sandwich cookies',
 'prosecco',
 'tomatoes in juice',
 'kashmiri chiles',
 'almonds',
 'herbes de provence',
 'panettone forms',
 'beef bouillon powder',
 'frozen waffle fries',
 'spicy horseradish',
 'coconut pudding mix',
 'whitefish fillets',
 'chili pepper',
 'fillets',
 'schnapps',
 'red tomatoes',
 'shrimp in shells',
 'boneless chuck steak',
 'brown bread',
 'wieners',
 'stalk leaves',
 'macaroni pasta',
 'kokum',
 'dashes pepper sauce',
 'frozen margarita mix',
 'jalapeno peppers',
 'canned',
 'spice ginger',
 'attieke',
 'stale bread',
 'wedge',
 'ring',
 'tamarind paste',
 'chestnut spread',
 'tip round roast',
 'walnuts',
 'orange cake mix',
 'lean pork butt',
 'dill weed',
 'gel food coloring',
 'chili sesame oil',
 'whole egg',
 'light cream',
 'italian cheese blend',
 'pickled pearl onions',
 'red snapper',
 'ricotta cheese',
 'whole new potatoes',
 'very soft butter',
 'apple filling',
 'cinnamon chips',
 'natural tomato sauce',
 'tomatoes in paste',
 'slice bacon',
 'absinthe',
 'leftover roast lamb',
 'sofrito',
 'day-old white bread',
 'chickens',
 'unsalted pistachios',
 'lightly torn spinach',
 'gumdrops',
 'english walnuts',
 'sushi-grade tuna',
 'solid white tuna',
 'makrut lime zest',
 'zucchini slices',
 'rock sugar candy',
 'beefsteak tomato',
 'watermelon schnapps',
 'blue cornmeal',
 'free sour cream',
 'mahi steaks',
 'japanese soy sauce',
 'sweet cream butter',
 'frozen udon noodles',
 'breadstick dough',
 'tomatoes jalapeno',
 'toothpicks',
 'white cauliflower',
 'tenkasu',
 'southwest seasoning',
 'smoked oysters',
 'orange rind',
 'root beer flavoring',
 'frozen pie crust',
 'smith apple - cored',
 'pork sausage',
 'cauliflowerets',
 'birds eye chiles',
 'bacon grease',
 'red thai chile',
 'broccoli stems',
 'fettucine',
 'dandelion flowers',
 'dogs natural casings',
 'fruit cocktail',
 'coconut yogurt',
 'ajwain seeds',
 'spanish sweet onion',
 'candied pineapple',
 'cheddar cheese chunk',
 'sweet pickle juice',
 'honeydew',
 'bulgur',
 'spicy yellow mustard',
 'baby spinach leaves',
 'bonito soup stock',
 'linguica sausage',
 'fig spread',
 'achiote powder',
 'rose extract',
 'sorghum grain',
 'potato -',
 'pomegranate juice',
 'sesame oil',
 'coarsely pecans',
 'pearl barley',
 'mace',
 'hulled barley',
 'baby-cut carrots',
 'lime cordial',
 'deli chicken breast',
 'cinnamon whiskey',
 'free vanilla yogurt',
 'provolone cheese',
 'mincemeat',
 'diagonally celery',
 'corn ears',
 'frozen green peas',
 'roughly mint leaves',
 'hulled hemp seeds',
 'brioche buns',
 'sweet butter',
 'sage stuffing mix',
 'maple',
 'slivered ginger',
 'firm banana',
 'baking powder',
 'baby bella mushrooms',
 'vitamin c powder',
 'beef tenderloin',
 'yakisoba noodles',
 'toasted flour',
 'red pepper flakes',
 'zafrani garam masala',
 'panko',
 'gari',
 'hamburger rolls',
 'burger patties',
 'cream cheese herbs',
 'mesophilic culture',
 'halved grapes',
 'brown mustard seeds',
 'steamed basmati rice',
 'gourds',
 'bitter cocoa powder',
 'bermuda onions',
 'matzo cake meal',
 'watermelon vodka',
 'tri-tip roast',
 'real bacon bits',
 'sweet dessert wine',
 'lardo',
 'multi-colored quinoa',
 'chicken tenders',
 'veal chops',
 'scotch fillet',
 'lemon bar mix',
 'half-and-half cream',
 'boysenberries',
 'refried black beans',
 'crusty french bread',
 'pizza dough',
 'rice',
 'very kirby cucumbers',
 'frozen carrots',
 'cookies',
 'drumettes',
 'wood ear mushrooms',
 'rice semolina',
 'iceberg salad',
 'dog',
 'low sodium salsa',
 'mashed huckleberries',
 'milk chocolate chips',
 'green plantains',
 'creme de cacao',
 'rosemary sprigs',
 'vital wheat gluten',
 'yellow sweet corn',
 'hatch green chile',
 'oysters',
 'stone-ground mustard',
 'sweet cherries',
 'red chile peppers',
 'buttermilk powder',
 'beer nut mix',
 'mini waffles',
 'aji pepper',
 'loosely brown sugar',
 'lean top round',
 'dill',
 'edamame in pod',
 'yellow peppers brine',
 'lean turkey',
 'papaya juice',
 'hummus',
 'smoky paprika',
 'very thick eggnog',
 'spring garlic stalks',
 'seeded tomato',
 'whole grain polenta',
 'crumbled feta cheese',
 'naan',
 'blue corn tortillas',
 'leftover ham',
 'white pepper',
 'lime granules',
 'baby carrots',
 'taco mild sauce',
 'chocolate curls',
 'pumpkin purée',
 'beef brisket',
 'emmental cheese',
 'sweet onion soup',
 'baby lettuce',
 'white tapioca pearls',
 'tenderloin fillets',
 'red sprinkles',
 'jumbo shrimp',
 'egg whites',
 'frozen tart cherries',
 'green papaya',
 'cavatelli pasta',
 'coarsely peanuts',
 'cubes as needed',
 'thai tea leaves',
 'thick-cut pork chops',
 'size flour tortillas',
 'nori strips to taste',
 'red grape tomatoes',
 'halibut steaks',
 'crab sticks',
 'garlic granules',
 'white mushrooms',
 'chuck pot roast',
 'duck breast',
 'cracker crust',
 'white peach',
 'stevia sweetener',
 'cassava flour',
 'kitchen bouquet',
 'baking cups',
 'bratwurst',
 'parsley sprigs',
 'paint stir sticks',
 'hominy',
 'creamed corn',
 'cut-up fruit',
 'beefsteak tomatoes',
 'red thai curry sauce',
 'black garlic bulbs',
 'culantro',
 'salmon filets',
 'pockets',
 'round london broil',
 'black bean sauce',
 'whole buttermilk',
 'sandhill plums',
 'venison ribs',
 'green peas',
 'black sprinkles',
 'fine cornmeal',
 'plastic mold',
 'uncle ready spanish',
 'coarsely cumin seeds',
 'shiraz wine',
 'sage leaves',
 'sweet potato puree',
 'jumbo lump crabmeat',
 'unprocessed bran',
 'beef sweetbreads',
 'russet potatoes',
 'bagel seasoning',
 'swiss cheese',
 'smith apple -',
 'sweet marsala wine',
 'chickpeas',
 'pearl tapioca',
 'tagliatelle pasta',
 'short-grain rice',
 'sodium nitrate',
 'stilton cheese',
 'cinnamon applesauce',
 'roast drippings',
 'salt cod steaks',
 'live',
 'salt',
 'chipotle flakes',
 'loosely basil',
 'sauterne wine',
 'ancho chile',
 'baby dill pickles',
 'multigrain flour',
 'ancho chilies',
 'baby basil leaves',
 'pink salt',
 'maple-flavored bacon',
 'cube',
 'mild red wine',
 'very lemon zest',
 'pear preserves',
 'white baby corn',
 'bell pepper - cored',
 'padron chile peppers',
 'sumac powder',
 'pepper sauce',
 'hibiscus salt',
 'deveined shrimp',
 'red miso paste',
 'merlot wine',
 'rib-eye steaks',
 'ice cream cones',
 'maple flavored syrup',
 'stuffing bread cubes',
 'frozen chicken wings',
 'chicken nuggets',
 'halved red grapes',
 'dill pickle juice',
 'curry ketchup',
 'ramps - washed',
 'tenderloin roasts',
 'saffron',
 'apricot brandy',
 'weiners',
 'paratha',
 'whole fennel seeds',
 'crema mexicana',
 'yellow potatoes',
 'raspberry juice',
 'cooled coffee',
 'flaked kosher salt',
 'grappa',
 'cherry peppers',
 'spiral-cut ham',
 'twinkies',
 'green beans - rinsed',
 'parmesan',
 'salmon',
 'leftover pinto beans',
 'pork belly',
 'jewish rye bread',
 'round roast',
 'yellow bell pepper',
 'mild country sausage',
 'grain tortillas',
 '- deboned',
 'frozen vegetables',
 'salted pork',
 'seasoned white beans',
 'beef consomme',
 'liquid sweetener',
 'quail',
 'smoked firm tofu',
 'beef cube steak',
 'washed spinach',
 'imitation crab legs',
 'vegan bouillon',
 'spearmint leaves',
 'garlic knots',
 'bosc pear',
 'rosé',
 'reduced spread',
 'lettuce hearts',
 'safflower',
 'lukewarm milk',
 'mozzarella balls',
 'cojita cheese',
 'saba',
 'muffin cup liners',
 'stock cube',
 'frozen cranberries',
 'combined',
 'tomatoes juice',
 'sandwich pepperoni',
 'apricot nectar',
 'green',
 'pitayas',
 'cloves garlic clove',
 'tongue',
 'crabs',
 'peppers seeds',
 'lemon extract',
 'bone-in beef chuck',
 'broccoli',
 'topping',
 'melon - halved',
 'green bananas',
 'cinnamon-sugar',
 'mild pepper jelly',
 'loquat preserves',
 'ancho chiles',
 'instant brown rice',
 'gulf shrimp',
 'instant',
 'pastry sheet',
 'beef filet',
 'dish pie crust',
 'rye flakes',
 'melba toast',
 'lightly ice',
 'camembert cheese',
 'kelp flakes',
 'drippings',
 'chile in adobo sauce',
 'grilling spray',
 'baguettes',
 'purslane',
 'porterhouse steak',
 'cured lemon',
 'liqueur',
 'blueberries - rinsed',
 'meatloaf mix',
 'dark german beer',
 'toasted oat cereal',
 'beef jerky',
 'chestnut flour',
 'frozen carrot slices',
 'soft brown sugar',
 'tomatoes herbs',
 'spanish chorizo',
 'cut',
 'macadamia nut',
 'orange food color',
 'prosciutto',
 'carolina gold rice',
 'tex-mex cheese blend',
 'steak ',
 'dark raisins',
 'bread cakes',
 'polish kielbasa',
 'roasted hazelnuts',
 'sweet bread rolls',
 'tips',
 'sweetened cereal',
 'rice vinegar',
 'whole carrots',
 'himalayan salt',
 'chicken gravy mix',
 'gai lan',
 'flaky sea salt',
 'persian cucumbers',
 'pigs tails',
 'unsalted almonds',
 'leeks',
 'french onion dip',
 'old bay seasoning"',
 'very',
 'frozen pineapple',
 'calamansi juice',
 'sauerkraut liquid',
 'milk bread',
 'beef flank steak',
 'skinless',
 'mache',
 'thai chile peppers',
 'pickle',
 'ube jam',
 'coconut cream',
 'wheat bran',
 'almond milk',
 'nutritional yeast',
 'rice crackers',
 'mexican-style sauce',
 'gelatin mold',
 'chorize sausage',
 'extra firm tofu',
 'smooth peanut butter',
 'no calorie sweetener',
 'sesame halva',
 'pinot gris',
 'red tomato',
 'strawberry soda',
 'worms',
 'kochujang',
 'shaved onion',
 'banana peppers',
 'hazelnut liqueur',
 'corn oil',
 'buttercream icing',
 'cut vegetables',
 'pepper-jack cheese',
 'chinese winter melon',
 'goji berries',
 'yellow corn meal',
 'process cheese sauce',
 'orange yogurt',
 'chorizo bites',
 'gluten free crackers',
 'gluten free elbows',
 'peach extract',
 'flour tortillas',
 'fatty pork butt',
 'cushaw squash',
 'black food coloring',
 'cherry chip cake mix',
 'cabbage - halved',
 'chia seed meal',
 'fruit cocktail syrup',
 'scalloped potatoes',
 'pellets',
 'melted margarine',
 'torn',
 'edible glitter',
 'round tip roast',
 'whole chestnuts',
 'imitation crab',
 'elderflower syrup',
 'roast beef',
 'banana liqueur',
 'buttermilk waffles',
 'malt powder',
 'made pizza crust',
 'black truffle salt',
 'hazelnut spread',
 'honeynut squashes',
 'damask rose petals',
 'lady apple',
 'pink sanding sugar',
 'turkey sausages',
 'muffins',
 'parmesan rind',
 'harissa',
 'basil oil',
 'corn flake cereal',
 'barbeque spice rub',
 'carambola',
 'lemon flavored vodka',
 'canned peaches',
 'dashi broth powder',
 'salad greens',
 'eggnog',
 'kiwi',
 'smoked turkey',
 'lemon pulp',
 'cherry yogurt',
 'chevre',
 'lemon marmalade',
 'red curry powder',
 'chicken parts',
 'queso asadero',
 'sausage links',
 'tomatoes onion',
 'spinach pasta',
 'gravy',
 'pepperoni',
 'frozen duckling',
 'lychee',
 'red food colouring',
 'red potato',
 'cucumber spears',
 'wasabi peas',
 'spicy seasoned salt',
 'artichoke hearts',
 'pesto dipping sauce',
 'limoncello liqueur',
 'bun',
 'amazn" prune juice',
 'coconut meat',
 'elk meat',
 'cranberry juice',
 'tea cookies',
 'tail-on shrimp',
 'clove garlic',
 'premium meat',
 'purple radishes',
 'grape tomatoes',
 'heads escarole',
 'ruby cacao wafers',
 'snow peas',
 'broken spaghetti',
 'persian rose petals',
 'peppers - stemmed',
 'black raspberries',
 'whole pompano fish',
 'strawberry',
 'cinnamon bun topping',
 'moroccan spice mix',
 'pumpkin spice syrup',
 'green pepper strips',
 'smoked cheddar salt',
 'popped popcorn',
 'blackened seasoning',
 'aquafaba',
 'tails',
 'reduced colby cheese',
 'firmly dates',
 'coarsely figs',
 'cacao nibs',
 'bitter chocolate',
 'pork cube steaks',
 'french green beans',
 'fully luncheon meat ',
 'lean sirloin',
 'milk as needed',
 'baking mix',
 'annatto powder',
 'peychauds',
 'ripened tomatoes',
 'boneless beef roast',
 'stalk',
 'roasted walnuts',
 'ginger stir-in paste',
 'red delicious apple',
 'to taste',
 'farro perlato',
 'demerara sugar',
 'carrot chips',
 'fish sauce',
 'pureed plums',
 'very persimmon pulp',
 'onion granules',
 'oil cooking spray',
 'whole pumpkin seeds',
 'bamboo fungus',
 'green leaf lettuce',
 'roughly cilantro',
 'speculoos cookies',
 'lamb chops',
 'uncured turkey bacon',
 'instant oatmeal',
 'pork shoulder',
 'twists',
 'pork tenderloin tips',
 'beef dogs',
 'doubanjiang',
 'gumbo file powder',
 'pureed pumpkin',
 'walnut oil',
 'lavender',
 'sweet sherry',
 'dark mexican beer',
 'amchur',
 'jamaican allspice',
 'soft pretzel rolls',
 'clear mint syrup',
 'crème fraîche',
 'grainy brown mustard',
 'garlic pepper blend',
 'cocoa powder',
 'prune plums',
 'berbere',
 'parmigiano-reggiano',
 'fine table salt',
 'dijon vinaigrette',
 'red sugar sprinkles',
 'roasted green chiles',
 'loosely spinach',
 'frozen corn kernels',
 'pasilla chilies',
 'puffed wheat cereal',
 ...}

In [45]:
from rapidfuzz import process, utils

def get_suggestions(user_input, choices, limit=5):
    results = process.extract(
        user_input, 
        choices, 
        processor=utils.default_process, 
        limit=20
    )
    
    processed_results = []
    
    # Pre-lowercase user_input once for efficiency
    search_term = user_input.lower()
    
    for text, score, index in results:
        adjusted_score = score
        
        # Penalty: Contains a space
        if " " in text:
            adjusted_score -= 5
            
        # Penalty: 4+ characters longer than input
        if len(text) >= len(user_input) + 4:
            adjusted_score -= 5

        # CORRECTED: Use .lower() method on the string
        # Also ensure we check against the lowercased text
        if search_term not in text.lower():
            adjusted_score -= 5
            
        processed_results.append((text, adjusted_score, index))
    
    processed_results.sort(key=lambda x: x[1], reverse=True)

    [match[0] for match in results if match[1] > 60]
    return [match[0] for match in processed_results[:limit]]

# Example Usage:
user_typing = "avoc"
print(get_suggestions(user_typing, unique_items))

['avocado', 'avocados', 'hass avocado', 'avocado oil', 'avocado wedges']

In [20]:
from rapidfuzz import process, utils


def get_suggestions(user_input, choices, limit=5):
    # We use utils.default_process to lowercase and remove non-alphanumeric chars
    # This makes the matching much more reliable
    results = process.extract(
        user_input, 
        choices, 
        processor=utils.default_process, 
        limit=20
    )
    
    # results returns a list of tuples: (string, score, index)
    return results #[match[0] for match in results if match[1] > 60]

# Example Usage:
user_typing = "tof"
print(get_suggestions(user_typing, unique_items))

[('toffee candy', 90.0, 140), ('fried tofu', 90.0, 144), ('soft tofu', 90.0, 395), ('toffee bits', 90.0, 805), ('smoked tofu', 90.0, 1156), ('firm tofu', 90.0, 2355), ('silken tofu', 90.0, 2581), ('toffee chips', 90.0, 2709), ('tofu', 85.71428571428572, 500), ('tongue', 72.0, 9), ('tomato soup', 72.0, 17), ('to garnish', 72.0, 53), ('pimento', 72.0, 62), ('topping', 72.0, 130), ('tomato puree', 72.0, 168), ('torn spinach', 72.0, 197), ('goya sofrito', 72.0, 227), ('torn lettuce', 72.0, 238), ('roma tomato', 72.0, 415), ('sweet potato', 72.0, 445)]

In [49]:
all_ingredients = {item['unit'] 
                   for ingredient_list in df['Ingredients_list'] 
                   for item in ingredient_list}
len(all_units)

False

In [54]:
all_units = {item['unit'] 
                   for ingredient_list in df['Ingredients_list'] 
                   for item in ingredient_list}
len(all_units)

1270

In [37]:
pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp310-cp310-win_amd64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp310-cp310-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------------------- ------ 1.3/1.5 MB 16.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 20.3 MB/s  0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3
Note: you may need to restart the kernel to use updated packages.

In [12]:
cuisine_mapping = {
    'Afghan': 'Middle Eastern',
    'African': 'African',
    'Algerian': 'African',
    'American': 'North American',
    'Amish': 'North American',
    'Argentine': 'Latin American',
    'Armenian': 'Middle Eastern',
    'Asian': 'East Asian',
    'Asian Inspired': 'Fusion & Inspired',
    'Australian': 'European',
    'Austrian': 'European',
    'Authentic': 'World / Generic',
    'Bangladeshi': 'South Asian',
    'Belgian': 'European',
    'Brazilian': 'Latin American',
    'British': 'European',
    'Cajun': 'North American',
    'Canadian': 'North American',
    'Caribbean': 'Latin American',
    'Chilean': 'Latin American',
    'Chinese': 'East Asian',
    'Chinese Inspired': 'Fusion & Inspired',
    'Colombian': 'Latin American',
    'Copycat': 'Fusion & Inspired',
    'Creole': 'North American',
    'Cuban': 'Latin American',
    'Czech': 'European',
    'Danish': 'European',
    'Dutch': 'European',
    'East African': 'African',
    'East And Southeast Asian': 'East Asian',
    'Eastern European': 'European',
    'Egyptian': 'Middle Eastern',
    'English': 'European',
    'Ethiopian': 'African',
    'European': 'European',
    'Filipino': 'East Asian',
    'Finnish': 'European',
    'French': 'European',
    'French Canadian': 'North American',
    'French Inspired': 'Fusion & Inspired',
    'Fusion': 'Fusion & Inspired',
    'German': 'European',
    'Greek': 'Mediterranean',
    'Greek Inspired': 'Fusion & Inspired',
    'Hawaiian': 'North American',
    'Hungarian': 'European',
    'Indian': 'South Asian',
    'Indian Inspired': 'Fusion & Inspired',
    'Indonesian': 'East Asian',
    'Inspired': 'Fusion & Inspired',
    'Irish': 'European',
    'Israeli': 'Middle Eastern',
    'Italian': 'Mediterranean',
    'Italian Inspired': 'Fusion & Inspired',
    'Jamaican': 'Latin American',
    'Japanese': 'East Asian',
    'Japanese Inspired': 'Fusion & Inspired',
    'Jewish': 'Jewish / Kosher',
    'Korean': 'East Asian',
    'Korean Inspired': 'Fusion & Inspired',
    'Kosher': 'Jewish / Kosher',
    'Latin': 'Latin American',
    'Latin American': 'Latin American',
    'Lebanese': 'Middle Eastern',
    'Malaysian': 'East Asian',
    'Mediterranean Inspired': 'Fusion & Inspired',
    'Mexican': 'Latin American',
    'Mexican Inspired': 'Fusion & Inspired',
    'Middle Eastern': 'Middle Eastern',
    'Middle Eastern Inspired': 'Fusion & Inspired',
    'Moroccan': 'African',
    'Native American': 'North American',
    'New England': 'North American',
    'New Zealand': 'European',
    'North African': 'African',
    'North American': 'North American',
    'Norwegian': 'European',
    'Oceanic': 'European',
    'Pakistani': 'South Asian',
    'Pennsylvania Dutch': 'North American',
    'Persian': 'Middle Eastern',
    'Peruvian': 'Latin American',
    'Polish': 'European',
    'Portuguese': 'European',
    'Puerto Rican': 'Latin American',
    'Russian': 'European',
    'Salvadoran': 'Latin American',
    'Scandinavian': 'European',
    'Scottish': 'European',
    'Sichuan': 'East Asian',
    'Sicilian': 'Mediterranean',
    'South African': 'African',
    'South American': 'Latin American',
    'South And Central Asian': 'South Asian',
    'Southern': 'North American',
    'Southwestern': 'North American',
    'Spanish': 'Mediterranean',
    'Sri Lankan': 'South Asian',
    'Swedish': 'European',
    'Swiss': 'European',
    'Syrian': 'Middle Eastern',
    'Tex Mex': 'Latin American',
    'Tex-Mex': 'Latin American',
    'Thai': 'East Asian',
    'Thai Inspired': 'Fusion & Inspired',
    'Tunisian': 'African',
    'Turkish': 'Middle Eastern',
    'U.S.': 'North American',
    'Uk And Ireland': 'European',
    'Ukrainian': 'European',
    'Venezuelan': 'Latin American',
    'Vietnamese': 'East Asian',
    'Welsh': 'European',
    'West African': 'African',
    'World': 'World / Generic'
}